DELETE  FROM ITEM;
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (1,'Ename','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (2,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (3,'Ename','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (4,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (5,'name','description',0.99);

