DELETE  FROM ITEM;
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (1,'Ename','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (2,'Ename','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (3,'Uname','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (4,'E','description',0.99);



