DELETE  FROM ITEM;
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (0,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (1,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (2,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (3,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (4,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (5,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (6,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (7,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (8,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (9,'name','description',0.99);



