DELETE  FROM ITEM;
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (0,'ame','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (1,'ame','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (2,'ame','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (3,'ame','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (4,'ame','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (5,'ame','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (6,'name','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (7,'ame','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (8,'ame','description',0.99);
INSERT INTO ITEM (ID,NAME,DESCRIPTION,PRICE) VALUES (9,'name','description',0.99);

